name: Create Release

on:
  push:
    tags:
      - 'v*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: |
            # Fortune Teller Release ${{ github.ref_name }}
            
            ## Changes in this release:
            
            ${{ contains(github.ref_name, 'v1.0') && '- Initial release with basic functionality' || '' }}
            ${{ contains(github.ref_name, 'v1.1') && '- Added random fortune selection and stressed mood option' || '' }} 